sudo: required
services:
  - docker

before_install:
  - docker build -t altinilke/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true altinilke/react-test npm test

after_success:
  - docker build -t altinilke/multi-cont_client ./client
  - docker build -t altinilke/multi-cont_nginx  ./nginx
  - docker build -t altinilke/multi-cont_server ./server
  - docker build -t altinilke/multi-cont_worker ./worker
  #Log in to the Docker Hub
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push images to the Docker Hub
  - docker push altinilke/multi-cont_client
  - docker push altinilke/multi-cont_nginx
  - docker push altinilke/multi-cont_server
  - docker push altinilke/multi-cont_worker